#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

data_dir: /vector-data-dir

sources:
  unifi_logs:
    type: syslog
    address: 0.0.0.0:514
    mode: udp

  vector_agent_logs:
    type: vector
    address: 0.0.0.0:8585
    tls:
      enabled: true
      ca_file: /etc/ssl/vector/ca.crt
      crt_file: /etc/ssl/vector/tls.crt
      key_file: /etc/ssl/vector/tls.key
      verify_certificate: true
#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

transforms:
  tag_unifi_logs:
    type: remap
    inputs:
      - unifi_logs
    source: |
      .@source = "unifi"
      .@dataset = "unifi"
      .@namespace = "default"

  parse_json:
    type: remap
    inputs:
      - vector_agent_logs
    source: |

      if is_string(.host) {
        .host = { "name": .host }
      }

      parsed, err = parse_json(.message)
      if err == null {
          . = merge!(., parsed)
          del(.message)
      }

  parse_syslog:
    type: remap
    inputs:
      - tag_unifi_logs
    source: |

      if is_string(.host) {
        .host = {"name": .host}
      }

      parsed, err = parse_syslog(.message)
      if err == null {
          del(.message)
          . = merge(.,parsed)
      }

  route_logs:
    type: route
    inputs:
      - parse_json
      - parse_syslog
    route:
      envoy_access_logs:
        type: vrl
        source: .@dataset == "kubernetes.envoy"
      hubble_flow_logs:
        type: vrl
        source: .@source == "hubble_flow"
      kubernetes_logs:
        type: vrl
        source: .@source == "kubernetes"
      kubernetes_audit_logs:
        type: vrl
        source: .@source == "kubernetes_audit"
      unifi_logs:
        type: vrl
        source: .@source == "unifi"
      vault_audit_logs:
        type: vrl
        source: '.@dataset == "kubernetes.vault" && (!is_null(.auth.accessor) || .@module == "expiration")'

  remap_envoy_access_logs:
    type: remap
    inputs:
      - route_logs.envoy_access_logs
    source: |
      .@dataset = "envoy.access"

  remap_hubble_flow_logs:
    type: remap
    inputs:
      - route_logs.hubble_flow_logs
    source: |

      if exists(.flow) {
        flow = del(.flow)
        . = merge!(., flow)

        .destination.id = del(.destination.ID)
        .destination.ip = del(.IP.destination)
        .destination.pod = del(.destination.pod_name)
        .destination.port = compact([.l4.TCP.destination_port, .l4.UDP.destination_port])[0]

        .event_type = .event_type.type
        .node = del(.node_name)
        .summary = del(.Summary)

        .source.id = del(.source.ID)
        .source.ip = del(.IP.source)
        .source.pod = del(.source.pod_name)
        .source.port = compact([.l4.TCP.source_port, .l4.UDP.source_port])[0]

        .type = del(.Type)

        del(.emitter)
        del(.ethernet)
        del(.host)
        del(.interface)
        del(.IP)
        del(.l4)
      }

  remap_kubernetes_logs:
    type: remap
    inputs:
      - route_logs.kubernetes_logs
    source: |
      .kubernetes.container = del(.kubernetes.container_name)
      .kubernetes.namespace = del(.kubernetes.pod_namespace)
      .kubernetes.node = del(.kubernetes.pod_node_name)
      .kubernetes.pod = del(.kubernetes.pod_name)

      del(.source_type)

  remap_kubernetes_audit_logs:
    type: remap
    inputs:
      - route_logs.kubernetes_audit_logs
    source: |
      .api_version = del(.apiVersion)
      .audit_id = del(.auditID)
      .impersonated_user = del(.impersonatedUser)
      .object_ref = del(.objectRef)
      .request_uri = del(.requestURI)
      .response_status = del(.responseStatus)
      .source_ips = del(.sourceIPs)
      .user_agent = del(.userAgent)

      del(.requestReceivedTimestamp)
      del(.stageTimestamp)

  remap_vault_audit_logs:
    type: remap
    inputs:
      - route_logs.vault_audit_logs
    source: |
      .@dataset = "vault.audit"
tests:
  - name: test_tag_unifi_logs
    inputs:
      - insert_at: tag_unifi_logs
        type: log
        log_fields:
          message: "{}"
    outputs:
      - extract_from: tag_unifi_logs
        conditions:
          - type: vrl
            source: |
              # Assert that the data stream for the logs follows 'logs-{dataset}-{namespace}'
              expected_destination = "logs-unifi-default"
              destination = "logs-" + string!(.@dataset) + "-" + string!(.@namespace)

              assert_eq!(.@source, "unifi")
              assert_eq!(.@dataset, "unifi")
              assert_eq!(.@namespace, "default")

              assert_eq!(destination, expected_destination)

  - name: test_parse_json_success
    inputs:
      - insert_at: parse_json
        type: log
        log_fields:
          message: '{ "user": "Retr0", "city": "Oakland", "affiliation": "DedSec" }'
    outputs:
      - extract_from: parse_json
        conditions:
          - type: vrl
            source: |
              assert_eq!(.user, "Retr0")
              assert_eq!(.city, "Oakland")
              assert_eq!(.affiliation, "DedSec")

              assert!(exists(.message) == false)

  - name: test_parse_json_error
    inputs:
      - insert_at: parse_json
        type: log
        log_fields:
          message: "[INFO] :: file.log - Non-JSON message"
    outputs:
      - extract_from: parse_json
        conditions:
          - type: vrl
            source: |
              expected_message = .message

              assert!(exists(.message) == true)
              assert_eq!(.message, expected_message)

  - name: test_parse_syslog_success
    inputs:
      - insert_at: parse_syslog
        type: log
        log_fields:
          message: "\u003c102\u003e1 2020-12-22T15:22:31.111Z vector-user.biz su 2666 ID389 - Something went wrong"
    outputs:
      - extract_from: parse_syslog
        conditions:
          - type: vrl
            source: |
              assert_eq!(.appname, "su")
              assert_eq!(.facility, "ntp")
              assert_eq!(.hostname, "vector-user.biz")
              assert_eq!(.message, "Something went wrong")
              assert_eq!(.msgid, "ID389")
              assert_eq!(.procid, 2666)
              assert_eq!(.severity, "info")
              assert_eq!(.timestamp, parse_timestamp!("2020-12-22T15:22:31.111Z", format: "%Y-%m-%dT%H:%M:%S.%3fZ", timezone: "UTC"))
              assert_eq!(.version, 1)

  - name: test_parse_syslog_error
    inputs:
      - insert_at: parse_syslog
        type: log
        log_fields:
          message: "[INFO] :: file.log - Non-syslog message"
    outputs:
      - extract_from: parse_syslog
        conditions:
          - type: vrl
            source: |
              expected_message = .message

              assert!(exists(.message) == true)
              assert_eq!(.message, expected_message)

  - name: test_remap_envoy_access_logs
    inputs:
      - insert_at: remap_envoy_access_logs
        type: log
        log_fields:
          "@dataset": "kubernetes.envoy"
    outputs:
      - extract_from: remap_envoy_access_logs
        conditions:
          - type: vrl
            source: |
              assert_eq!(.@dataset, "envoy.access")

  - name: test_remap_hubble_flow_logs
    inputs:
      - insert_at: remap_hubble_flow_logs
        type: log
        log_fields:
          node_name: node-01
          flow:
            emitter:
              name: Hubble
              version: test-version
            ethernet:
              source: aa:aa:aa:aa:aa:aa
              destination: bb:bb:bb:bb:bb:bb
            IP:
              source: "1.1.1.1"
              destination: "8.8.8.8"
              ipVersion: IPv4
            l4:
              TCP:
                source_port: 47100
                destination_port: 53
            source:
              ID: 21
              identity: 12345
              cluster_name: test
              namespace: test-namespace-alpha
              labels: []
              pod_name: test-pod-1
              workloads: []
            destination:
              ID: 9001
              identity: 22222
              cluster_name: test
              namespace: test-namespace-delta
              labels: []
              pod_name: test-pod-2
              workloads: []
            Type: L3_L4
            node_name: node-01
            event_type:
              type: "4"
            interface:
              index: 20
              name: test
            Summary: UDP
    outputs:
      - extract_from: remap_hubble_flow_logs
        conditions:
          - type: vrl
            source: |
              assert_eq!(.destination.id, 9001)
              assert_eq!(.destination.ip, "8.8.8.8")
              assert_eq!(.destination.pod, "test-pod-2")
              assert_eq!(.destination.port, 53)

              assert_eq!(.event_type, "4")
              assert_eq!(.node, "node-01")
              assert_eq!(.summary, "UDP")

              assert_eq!(.source.id, 21)
              assert_eq!(.source.ip, "1.1.1.1")
              assert_eq!(.source.pod, "test-pod-1")
              assert_eq!(.source.port, 47100)

              assert_eq!(.type, "L3_L4")

              assert!(exists(.flow) == false)
              assert!(exists(.emitter) == false)
              assert!(exists(.ethernet) == false)
              assert!(exists(.interface) == false)
              assert!(exists(.l4) == false)

  - name: test_remap_kubernetes_logs
    inputs:
      - insert_at: remap_kubernetes_logs
        type: log
        log_fields:
          file: /var/log/test-file.log
          kubernetes:
            container_name: test
            pod_namespace: test-namespace
            pod_node_name: test-node
            pod_name: test-pod
    outputs:
      - extract_from: remap_kubernetes_logs
        conditions:
          - type: vrl
            source: |
              assert_eq!(.kubernetes.container, "test")
              assert_eq!(.kubernetes.namespace, "test-namespace")
              assert_eq!(.kubernetes.node, "test-node")
              assert_eq!(.kubernetes.pod, "test-pod")

              assert!(exists(.kubernetes.container_name) == false)
              assert!(exists(.kubernetes.pod_namespace) == false)
              assert!(exists(.kubernetes.pod_node_name) == false)
              assert!(exists(.kubernetes.pod_name) == false)
              assert!(exists(.source_type) == false)

  - name: test_remap_kubernetes_audit_logs
    inputs:
      - insert_at: remap_kubernetes_audit_logs
        type: log
        log_fields:
          apiVersion: audit.k8s.io/v1
          auditID: 11111111-1111-1111-1111-111111111111
          impersonatedUser:
            username: test-user
          objectRef:
            name: test
          requestURI: /apis/test/v1beta3
          responseStatus:
            code: 200
          sourceIPs: ["1.1.1.1"]
          userAgent: test-client
    outputs:
      - extract_from: remap_kubernetes_audit_logs
        conditions:
          - type: vrl
            source: |
              expected_impersonated_user = {
                "username": "test-user"
              }
              expected_object_ref = {
                "name": "test"
              }
              expected_response_status = {
                "code": 200
              }

              assert_eq!(.api_version, "audit.k8s.io/v1")
              assert_eq!(.audit_id, "11111111-1111-1111-1111-111111111111")
              assert_eq!(.impersonated_user, expected_impersonated_user)
              assert_eq!(.object_ref, expected_object_ref)
              assert_eq!(.request_uri, "/apis/test/v1beta3")
              assert_eq!(.response_status, expected_response_status)
              assert_eq!(.source_ips, ["1.1.1.1"])
              assert_eq!(.user_agent, "test-client")

              assert!(exists(.requestReceivedTimestamp) == false)
              assert!(exists(.stageTimestamp) == false)

  - name: test_remap_vault_audit_logs
    inputs:
      - insert_at: remap_vault_audit_logs
        type: log
        log_fields:
          "@dataset": "vault.audit"
    outputs:
      - extract_from: remap_vault_audit_logs
        conditions:
          - type: vrl
            source: |
              assert_eq!(.@dataset, "vault.audit")