#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Relevant Sources
# ------------------------------------------------------------------------------
# File: https://vector.dev/docs/reference/configuration/sources/file/
#
# Kubernetes: https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/
# ------------------------------------------------------------------------------

data_dir: /vector-data-dir

sources:
  unifi_logs:
    type: syslog
    address: 0.0.0.0:514
    mode: udp
    permit_origin:
      - 10.20.1.0/24
