#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

data_dir: /vector-data-dir

sources:
  unifi_logs:
    type: syslog
    address: 0.0.0.0:514
    mode: udp

  vector_agent_logs:
    type: vector
    address: 0.0.0.0:8585
    tls:
      enabled: true
      ca_file: /etc/ssl/ilysium/ca.crt
      crt_file: /etc/ssl/vector/tls.crt
      key_file: /etc/ssl/vector/tls.key
      verify_certificate: true
