apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-ca
  namespace: vector
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDVjCCAj6gAwIBAgIRAN1nYO+pYIEPRxWg/H6z9MAwDQYJKoZIhvcNAQELBQAw
    NTEWMBQGA1UECxMNZWxhc3RpY3NlYXJjaDEbMBkGA1UEAxMSZWxhc3RpY3NlYXJj
    aC1odHRwMB4XDTI2MDQyNjE4NDE0MloXDTI3MDQyNjE4NTE0MlowNTEWMBQGA1UE
    CxMNZWxhc3RpY3NlYXJjaDEbMBkGA1UEAxMSZWxhc3RpY3NlYXJjaC1odHRwMIIB
    IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA84IgZmocwOhaooXQuhxS2bQF
    TGKJ1bsNuKTy9/FAGWXSX7cBXsqnRyOzNaAluXdUL2bq/vtF7JvdthT1xVsGoxJV
    B1T69bQRnGhLOtOddu7EwIU9PcUrO5Ul6WW8tIMhY2HkKBiaVxIdP2u84LrWovu1
    96YfQAnCcmTvvXjm3UQ5vf3PUnOrtaGDh+qXRzv4pCZah8QEWu6/OdS+OM6wMiDe
    JEoTGzMV+k5qQSPIqb2+dremg779qX0PwTp0zrQ7LgRcLIdxSlxDqKioBNdazh0f
    CM2z+JGRNoI8C8ErCMWwQnzKme8JLaoAOPLzcZwuqgeyMaTF5hbuHBsGpnYsUQID
    AQABo2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
    AQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMNlQ872k4SAYfjj01YZ
    Bu9kOxibMA0GCSqGSIb3DQEBCwUAA4IBAQAQoO6Szlm7CohnUuDnaCJKWba0qqgj
    Nk/Jw6kemGGoq9jIinVKuo7dUgzTICRZL0XUKllF5g8AnojUYlQaMrNmUo2At6LA
    CIs1Q59d2etllLYfiz0uexrBE4nieT67heQ+fYMsFDpZ3aJB2tuRMVpNtw5UGqI2
    aLf7kD51jVKYWdb8/ROxAIqIQ5gtU28BLjjcUUY1jg9pN4UmhL66S1VDV0UZx2pY
    9u7Nd7bTIlykGuJfUC9G2jvyshF5ntOVEqzD1B2hvqUVOROeSG33Z1MBb6BhGzsQ
    80Z1NWihQbl0gm6RMhFmoSJEjWj+xeCxsomPtIjdJtWXpENLb79bf7WM
    -----END CERTIFICATE-----
