apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elastic-ca.yml
  - secret-store.yml
  - vector.yml
configMapGenerator:
  - name: vector-agent-config
    files:
      - ../../config/agent/sources.yml
      - ../../config/agent/transforms.yml
      - ../../config/agent/sinks.yml
  - name: vector-aggregator-config
    files:
      - ../../config/aggregator/sources.yml
      - ../../config/aggregator/transforms.yml
      - ../../config/aggregator/sinks.yml
generatorOptions:
  disableNameSuffixHash: true
