#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

sources:
  
  # Reference: https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/
  # -----------------------------------------------------------------------------------
  kubernetes_logs:
    type: kubernetes_logs
    auto_partial_merge: true
    self_node_name: "${VECTOR_SELF_NODE_NAME}"
