#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

transforms:
  tag_hubble_flow_logs:
    type: remap
    inputs:
      - hubble_flow_logs
    source: |
      .@source = "hubble_flow"
      .@dataset = "hubble.flow"
      .@namespace = "default"

  tag_kubernetes_logs:
    type: remap
    inputs:
      - kubernetes_logs
    source: |
      .@source = "kubernetes"
      .@dataset = "kubernetes." + string!(.kubernetes.pod_namespace)
      .@namespace = "default"

  tag_kubernetes_audit_logs:
    type: remap
    inputs:
      - kubernetes_audit_logs
    source: |
      .@source = "kubernetes_audit"
      .@dataset = "kubernetes.audit"
      .@namespace = "default"

