#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                                   Configuration
#
# ------------------------------------------------------------------------------
# Website: https://vector.dev
# Docs: https://vector.dev/docs
# Chat: https://chat.vector.dev
# ------------------------------------------------------------------------------

# Relevant Transforms
# ------------------------------------------------------------------------------
# Dedupe - Deduplicate events to reduce data volume by eliminating identical events:
# https://vector.dev/docs/reference/configuration/transforms/dedupe/
#
# Filter - Filter events based on a set of conditions:
# https://vector.dev/docs/reference/configuration/transforms/filter/
#
# Remap - Modify observability data as it passes through the topology using Vector Remap Language (VRL):
# https://vector.dev/docs/reference/configuration/transforms/remap/
#
# Route - Split a stream of events into multiple sub-streams based on user-supplied conditions:
# https://vector.dev/docs/reference/configuration/transforms/route/
#
# Throttle - Rate limit logs passing through a topology:
# https://vector.dev/docs/reference/configuration/transforms/throttle/
# ------------------------------------------------------------------------------

transforms:
  tag_hubble_flow_logs:
    type: remap
    inputs:
      - hubble_flow_logs
    source: |
      .@source = "hubble_flow"
      .@dataset = "hubble-flow"
      .@namespace = "platform"

  tag_kubernetes_logs:
    type: remap
    inputs:
      - kubernetes_logs
    source: |
      .@source = "kubernetes"
      .@dataset, err = "kubernetes-" + .kubernetes.container_name
      .@namespace = .kubernetes.pod_namespace

      if err == null {
        return null
      }

  tag_kubernetes_audit_logs:
    type: remap
    inputs:
      - kubernetes_audit_logs
    source: |
      .@source = "kubernetes_audit"
      .@dataset = "kubernetes-audit"
      .@namespace = "platform"

  tag_vault_audit_logs:
    type: remap
    inputs:
      - vault_audit_logs
    source: |
      .@source = "vault_audit"
      .@dataset = "vault-audit"
      .@namespace = "platform"

  parse_json:
    type: remap
    inputs:
      - tag_hubble_flow_logs
      - tag_kubernetes_logs
      - tag_kubernetes_audit_logs
      - tag_vault_audit_logs
    source: |
      parsed, err = parse_json(.message)
      if err == null {
          . = merge!(., parsed)
          del(.message)
      }

  route_by_source:
    type: route
    inputs:
      - parse_json
    route:
      hubble: .@source == "hubble_flow"
      kubernetes: .@source == "kubernetes"
      kubernetes_audit: .@source == "kubernetes_audit"
      vault: .@source == "vault_audit"

  remap_hubble_flow_logs:
    type: remap
    inputs:
      - route_by_source.hubble
    source: |
      flow = del(.flow)

      . = merge!(., flow)

      .destination.id = del(.destination.ID)
      .destination.ip = del(.IP.destination)
      .destination.pod = del(.destination.pod_name)
      .destination.port = compact([.l4.TCP.destination_port, .l4.UDP.destination_port])[0]

      .event_type = .event_type.type
      .node = del(.node_name)
      .protocol = del(.Summary)

      .source.id = del(.source.ID)
      .source.ip = del(.IP.source)
      .source.pod = del(.source.pod_name)
      .source.port = compact([.l4.TCP.source_port, .l4.UDP.source_port])[0]

      .type = del(.Type)

      del(.emitter)
      del(.ethernet)
      del(.interface)
      del(.l4)

  remap_kubernetes_logs:
    type: remap
    inputs:
      - route_by_source.kubernetes
    source: |
      .kubernetes.container = del(.kubernetes.container_name)
      .kubernetes.namespace = del(.kubernetes.pod_namespace)
      .kubernetes.node = del(.kubernetes.pod_node_name)
      .kubernetes.pod = del(.kubernetes.pod_name)

      del(.source_type)

  remap_kubernetes_audit_logs:
    type: remap
    inputs:
      - route_by_source.kubernetes_audit
    source: |
      .api_version = del(.apiVersion)
      .audit_id = del(.auditID)
      .impersonated_user = del(.impersonatedUser)
      .object_ref = del(.objectRef)
      .request_uri = del(.requestURI)
      .response_status = del(.responseStatus)
      .source_ips = del(.sourceIPs)
      .user_agent = del(.userAgent)

      del(.requestReceivedTimestamp)
      del(.stageTimestamp)

  remap_vault_audit_logs:
    type: remap
    inputs:
      - route_by_source.vault
    source: |
      del(.request.namespace)
