name: Test Vector Configuration

on:
  pull_request:
    paths:
      - config/**
      - tests/**

jobs:
  test-config:
    runs-on: ubuntu-latest
    container:
      image: timberio/vector:nightly-alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Vector Configuration
        run: |
          vector validate config/agent/**/*.yml --no-environment
          vector validate config/aggregator/**/*.yml --no-environment

      - name: Test Vector Configuration
        run: |
          vector test \
            config/**/*.yml \
            tests/**/*.yml
